export const IS_CITY = 'IS_CITY'
export const NAV_LIST = 'NAV_LIST'
export const CITY_LIST = 'CITY_LIST'
export const HOT_LIST = 'HOT_LIST'
export const HOTEL_LIST = 'HOTEL_LIST'
export const MEMBER_DETAIL = 'MEMBER_DETAIL'
